# Simple workflow for deploying static content to GitHub Pages
name: Build and publish to NPM

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - 'main'
    paths:
      - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run yarn install
        run: yarn install
        
#       - name: Run yarn test
#         run: yarn run test
        
      - name: Run yarn build
        run: yarn run build
      
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.0.31
        id: version-bump
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
      
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: './dist/'
          generateReleaseNotes: true
          tag: ${{ steps.version-bump.outputs.newTag }}
