# Simple workflow for deploying static content to GitHub Pages
name: Run Unit Tests

on:
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run yarn install
        run: yarn install
      - name: Run yarn test
        run: yarn run test
      - name: Report LCOV
        uses: checkity/upload@v1
        with:
          badge-enabled: true
          badge-token: 'b-links-coverage'
          diff-enabled: false
          file-pattern: 'coverage/lcov.info'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
